version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=cuarto
      - DB_USER=root
      - DB_PASS=root

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuarto
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
